python /home/himanshu/megatron_dir/Megatron-LM/examples/lora/train_qwen3coder_unsloth.py \
  --model_name unsloth/Qwen3-1.7B \
  --train_file /home/shared/megatron_dir/data/sft/train_data_sft_480b_375_swe_bench_shuf.jsonl \
  --eval_file /home/shared/megatron_dir/data/sft/train_data_sft_480b_375_swe_bench_shuf_eval.jsonl \
  --output_dir /home/shared/megatron_dir/output/himanshu/qwen3coder30b-unsloth \
  --max_seq_len 32768 \
  --per_device_train_bs 1 \
  --per_device_eval_bs 1 \
  --grad_accum 8 \
  --epochs 4 \
  --logging_steps 1 \
  --lr 2e-4 \
  --weight_decay 0.01 \
  --use_qlora \
  --bf16 \